name = "ManpowerPlanning"
uuid = "6098a329-8c96-5c9c-9c97-4012e2806895"
license = "MIT"
authors = ["Johan Van Kerckhoven <johan.vankerckhoven@gmail.com>"]
version = "2.0.8"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
SimJulia = "428bdadb-6287-5aa5-874b-9969638295fd"

[compat]
julia = ">=0.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
